"""Add Agenda model

Revision ID: 08e66d8bc907
Revises: a2b64d8d1e73
Create Date: 2026-08-01 00:01:35.421336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08e66d8bc907'
down_revision = 'a2b64d8d1e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('waktu_mulai', sa.Time(), nullable=True),
    sa.Column('waktu_selesai', sa.Time(), nullable=True),
    sa.Column('lokasi', sa.String(length=255), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=True),
    sa.Column('is_aktif', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda')
    # ### end Alembic commands ###
