"""Add ArsipDokumen with User Access Control

Revision ID: a2b64d8d1e73
Revises: 289e859d5282
Create Date: 2026-07-31 23:37:07.281737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2b64d8d1e73'
down_revision = '289e859d5282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arsip_dokumen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.Text(), nullable=False),
    sa.Column('akses_tipe', sa.String(length=20), nullable=False),
    sa.Column('is_aktif', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arsip_dokumen_allowed_users',
    sa.Column('arsip_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arsip_id'], ['arsip_dokumen.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('arsip_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arsip_dokumen_allowed_users')
    op.drop_table('arsip_dokumen')
    # ### end Alembic commands ###
